% -------------------------------------------------------------------
%  Generated by MATLAB on 29-Apr-2023 23:04:00
%  MATLAB version: 9.14.0.2206163 (R2023a)
% -------------------------------------------------------------------

% Create and configure Variant Configurations object.
cfgVariant = Simulink.VariantConfigurationData;


% Add variant configurations.
configurationsList = struct('Name', {}, 'ControlVariables', {}, 'Description', {});


% Add configuration AtcVantCfg.


% Configure control variable VrntMtrTypeS0I1.
VrntMtrTypeS0I1 = 0;

% Configure control variable VrntDynamoMdeS0T1.
VrntDynamoMdeS0T1 = 1;

% Associate variant control variables for configuration AtcVantCfg.
configurationsList(end+1) = struct('Name' , 'AtcVantCfg', 'ControlVariables', cell2struct({'VrntMtrTypeS0I1', VrntMtrTypeS0I1, 'base workspace';'VrntDynamoMdeS0T1', VrntDynamoMdeS0T1, 'base workspace'}, {'Name', 'Value', 'Source'}, 2), 'Description', '');
cfgVariant.setConfigurations(configurationsList);
