function cellInfo = test(varargin) 
% TEST returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'X_H01SMDE', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'mSMDE_uFlagInverterOut', 1, 'uint16', 'real', 'Sample', 'Fixed', 0, 256, sprintf('N/A'), sprintf('■ 설명: Allow Operation 신호 (0: 구정 정지, 1: 구동)')}; ...
{'mSMDE_sSpdRefInSeqOut', 1, 'single', 'real', 'Sample', 'Fixed', 0, 1, sprintf('N/A'), sprintf('■ 설명: Speed Slop 제어를 위한 이전 지령 속도')}; ...
{'mSMDE_sSpdLimit', 1, 'single', 'real', 'Sample', 'Fixed', -3500, 3500, sprintf('N/A'), sprintf('■ 설명: 속도 제한값')}; ...
{'mSMDE_sSpdRef', 1, 'single', 'real', 'Sample', 'Fixed', 0, 1, sprintf('N/A'), sprintf('■ 설명: 속도 지령')}; ...
{'mSMDE_sPstRef', 1, 'single', 'real', 'Sample', 'Fixed', 0, 1, sprintf('N/A'), sprintf('■ 설명: 위치 지령')}; ...
{'mSMDE_sIfFreqSeqOut', 1, 'single', 'real', 'Sample', 'Fixed', 0, 1, sprintf('N/A'), sprintf('■ 설명: 모터 구동 모드 (0_IO/1_VF/2_V/4_CURR/8_TQ/16_SPD/32_PST/64_VALIGN/128_ALIGN/256_IF)')}; ...
{'mSMDE_uMtrCtrlMde', 1, 'uint16', 'real', 'Sample', 'Fixed', 0, 256, sprintf('N/A'), sprintf('■ 설명: 운영 모드 (모터 구동 모드)')}; ...
{'mSMDE_uOprState', 1, 'uint16', 'real', 'Sample', 'Fixed', 0, 63, sprintf('N/A'), sprintf('■ 설명: 운영 모드 (1H : Standby / 2H : JOG / 4H : MPG_JOG / 8H: Operating / 16H : Wait / 32H: Origin)')}; ...
{'mSMDE_uFlagSaveEncOrigin', 1, 'uint16', 'real', 'Sample', 'Fixed', 0, 1, sprintf('N/A'), sprintf('■ 설명: 엔코더 원점 저장 활성화 신호')}; ...
{'mSMDE_uFlagResetEnc', 1, 'uint16', 'real', 'Sample', 'Fixed', 0, 1, sprintf('N/A'), sprintf('■ 설명: 엔코더 멀티턴 리셋 활성화 신호')}; ...
{'mSMDE_i64PstOrigin', 1, 'int64', 'real', 'Sample', 'Fixed', -9.223372036854776e+18, 9.223372036854776e+18, sprintf('N/A'), sprintf('■ 설명: Encoder 원점 정보')}; ...
{'mSMDE_i64PstRef', 1, 'int64', 'real', 'Sample', 'Fixed', -9.223372036854776e+18, 9.223372036854776e+18, sprintf('N/A'), sprintf('■ 설명: Position Reference')}; ...
{'mSMDE_sRefAngleDisp', 1, 'single', 'real', 'Sample', 'Fixed', -3600, 3600, sprintf('N/A'), sprintf('■ 설명: 터렛 지령 위치 모니터 값')}; ...
{'mSMDE_sActAngleDisp', 1, 'single', 'real', 'Sample', 'Fixed', -3600, 3600, sprintf('N/A'), sprintf('■ 설명: 터렛 지령 위치 모니터 값')}; ...
{'mSMDE_sAngleErrDisp', 1, 'single', 'real', 'Sample', 'Fixed', -3600, 3600, sprintf('N/A'), sprintf('■ 설명: 터렛 현재 위치  오차 모니터 값')}; ...
{'mSMDE_sRefAngle', 1, 'single', 'real', 'Sample', 'Fixed', -3600, 3600, sprintf('N/A'), sprintf('■ 설명: 터렛 지령 위치')}; ...
{'mSMDE_sActAngle', 1, 'single', 'real', 'Sample', 'Fixed', -3600, 3600, sprintf('N/A'), sprintf('■ 설명: 터렛 현재 위치')}; ...
{'mSMDE_sAngleErr', 1, 'single', 'real', 'Sample', 'Fixed', -3600, 3600, sprintf('N/A'), sprintf('■ 설명: 터렛 위치 오차')}; ...
{'mSMDE_uExOut', 1, 'Bus: X_H01EXO', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
